import turtle as t
t.screensize(1920, 1080)
t.speed(10)
t.pensize(3)
t.hideturtle()

t.penup()
t.goto(-200, -50)
t.pendown()
t.color("blue")
t.begin_fill()
t.right(180 / 3)
t.circle(40, steps=3)
t.end_fill()

t.penup()
t.goto(-100, -50)
t.pendown()
t.color("black")
t.begin_fill()
t.setheading(0)
t.right(180 / 4)
t.circle(40, steps=4)
t.end_fill()

t.penup()
t.goto(0, -50)
t.pendown()
t.color("red")
t.begin_fill()
t.setheading(0)
t.right(180 / 5)
t.circle(40, steps=5)
t.end_fill()

t.penup()
t.goto(100, -50)
t.pendown()
t.color("yellow")
t.begin_fill()
t.setheading(0)
t.right(180 / 6)
t.circle(40, steps=6)
t.end_fill()

t.penup()
t.goto(200, -50)
t.pendown()
t.color("green")
t.begin_fill()
t.setheading(0)
t.right(180 / 8)
t.circle(40, steps=8)
t.end_fill()

t.penup()
t.goto(-100, 50)
t.color("red")
t.write("Cool Colorful Shapes", font = ("Times", 22, "normal"))

t.done()